services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN} 
      GROQ_API_KEY: ${GROQ_API_KEY}
    develop: 
      watch:
        - action: rebuild
          path: .
  db:
     image: postgres
     restart: always
     user: postgres
       
     volumes:
       - db-data:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=example
       - POSTGRES_PASSWORD=princy
     expose:
       - 5432
     healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5
volumes:
   db-data:





   